pub(crate) const SOURCE_REGISTRY_VERSION: &str = "2026-06-25";
pub(crate) const UI_CONTRACT_VERSION: &str = "2026-06-25";

use super::contract::{
    RUNTIME_FACT_KEY_PROVIDER_CONFIGURED_DEFAULT_MODEL,
    RUNTIME_FACT_KEY_PROVIDER_CONFIGURED_DEFAULT_PROVIDER, RUNTIME_FACT_KEY_PROVIDER_CURRENT_MODEL,
    RUNTIME_FACT_KEY_PROVIDER_CURRENT_MODEL_GENERATED, RUNTIME_FACT_KEY_PROVIDER_CURRENT_PROVIDER,
    RUNTIME_FACT_KEY_PROVIDER_CURRENT_ROUTE_TYPE, RUNTIME_FACT_KEY_PROVIDER_LAST_COMPLETED_MODEL,
    RUNTIME_FACT_KEY_PROVIDER_LAST_COMPLETED_PROVIDER,
    RUNTIME_FACT_KEY_PROVIDER_LAST_COMPLETED_RUN_ID, RUNTIME_FACT_KEY_PROVIDER_PLANNED_MODEL,
    RUNTIME_FACT_KEY_PROVIDER_PLANNED_PROVIDER, RUNTIME_FACT_KEY_PROVIDER_PLANNED_ROUTE_TYPE,
    RUNTIME_FACT_KEY_PROVIDER_PREFLIGHT_STATUS,
};

pub(crate) fn provider_route_fact_keys() -> Vec<&'static str> {
    vec![
        RUNTIME_FACT_KEY_PROVIDER_CURRENT_PROVIDER,
        RUNTIME_FACT_KEY_PROVIDER_CURRENT_MODEL,
        RUNTIME_FACT_KEY_PROVIDER_CURRENT_ROUTE_TYPE,
        RUNTIME_FACT_KEY_PROVIDER_CURRENT_MODEL_GENERATED,
        RUNTIME_FACT_KEY_PROVIDER_LAST_COMPLETED_PROVIDER,
        RUNTIME_FACT_KEY_PROVIDER_LAST_COMPLETED_MODEL,
        RUNTIME_FACT_KEY_PROVIDER_LAST_COMPLETED_RUN_ID,
        RUNTIME_FACT_KEY_PROVIDER_CONFIGURED_DEFAULT_PROVIDER,
        RUNTIME_FACT_KEY_PROVIDER_CONFIGURED_DEFAULT_MODEL,
        RUNTIME_FACT_KEY_PROVIDER_PLANNED_PROVIDER,
        RUNTIME_FACT_KEY_PROVIDER_PLANNED_MODEL,
        RUNTIME_FACT_KEY_PROVIDER_PLANNED_ROUTE_TYPE,
        RUNTIME_FACT_KEY_PROVIDER_PREFLIGHT_STATUS,
    ]
}
