pub mod a2a;
pub mod agent;
pub mod builder;
pub mod calibration;
pub mod chat;
pub mod diagnostics;
pub mod feedback;
// Hermes module removed: replaced by agent::reasoning module
pub mod execution;
pub mod life_model;
pub mod mcp;
pub mod memory;
pub mod metrics;
pub mod proactive;
pub mod proposal;
pub mod router;
pub mod settings;
pub mod state;
pub mod version;
