//! Proactive check-in engine: generates suggestions for daily briefs,
//! weekly reviews, stale goal reminders, pending proposal alerts,
//! and state check-in prompts. All outputs are declarative suggestions
//! — the actual AgentLoop execution is handled by the Tauri shell.

use crate::life_model::LifeModel;
use serde::{Deserialize, Serialize};

/// A proactive suggestion generated by the check-in engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProactiveSuggestion {
    pub id: String,
    pub category: ProactiveCategory,
    pub title: String,
    pub prompt: String,
    pub priority: ProactivePriority,
    /// Whether the user has seen this suggestion
    pub seen: bool,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProactiveCategory {
    DailyBrief,
    WeeklyReview,
    StaleGoal,
    PendingProposal,
    StateCheckin,
}

impl std::fmt::Display for ProactiveCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProactiveCategory::DailyBrief => write!(f, "daily_brief"),
            ProactiveCategory::WeeklyReview => write!(f, "weekly_review"),
            ProactiveCategory::StaleGoal => write!(f, "stale_goal"),
            ProactiveCategory::PendingProposal => write!(f, "pending_proposal"),
            ProactiveCategory::StateCheckin => write!(f, "state_checkin"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProactivePriority {
    Low,
    Medium,
    High,
}

impl std::fmt::Display for ProactivePriority {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProactivePriority::Low => write!(f, "low"),
            ProactivePriority::Medium => write!(f, "medium"),
            ProactivePriority::High => write!(f, "high"),
        }
    }
}

/// Configuration for the proactive engine.
pub struct ProactiveConfig {
    /// Days before a goal is considered stale (no progress update)
    pub stale_goal_days: i64,
    /// Days before a pending proposal triggers a reminder
    pub proposal_reminder_days: i64,
    /// Whether daily brief is enabled
    pub enable_daily_brief: bool,
    /// Whether weekly review is enabled
    pub enable_weekly_review: bool,
    /// Whether state check-in is enabled
    pub enable_state_checkin: bool,
    /// Maximum suggestions per check-in round
    pub max_suggestions: usize,
}

impl Default for ProactiveConfig {
    fn default() -> Self {
        Self {
            stale_goal_days: 7,
            proposal_reminder_days: 3,
            enable_daily_brief: true,
            enable_weekly_review: true,
            enable_state_checkin: true,
            max_suggestions: 5,
        }
    }
}

/// Engine that generates proactive suggestions from LifeModel state.
#[derive(Default)]
pub struct ProactiveEngine {
    config: ProactiveConfig,
}

impl ProactiveEngine {
    pub fn new(config: ProactiveConfig) -> Self {
        Self { config }
    }

    /// Generate all proactive suggestions for the current LifeModel state.
    pub fn generate_suggestions(
        &self,
        life_model: &LifeModel,
        pending_proposal_count: usize,
        high_risk_proposal_count: usize,
        oldest_proposal_days: Option<i64>,
    ) -> Vec<ProactiveSuggestion> {
        let mut suggestions = Vec::new();
        let now = chrono::Utc::now();

        // Daily brief
        if self.config.enable_daily_brief {
            suggestions.push(self.daily_brief_suggestion(life_model, now));
        }

        // Weekly review (only on Mondays or if never done)
        if self.config.enable_weekly_review {
            suggestions.push(self.weekly_review_suggestion(life_model, now));
        }

        // Stale goal detection
        for goal_text in self.detect_stale_goals(life_model) {
            suggestions.push(self.stale_goal_suggestion(&goal_text, now));
        }

        // Pending proposal reminder
        if pending_proposal_count > 0 {
            if let Some(reminder) = self.proposal_reminder_suggestion(
                pending_proposal_count,
                high_risk_proposal_count,
                oldest_proposal_days,
                now,
            ) {
                suggestions.push(reminder);
            }
        }

        // State check-in (if last recorded state is old)
        if self.config.enable_state_checkin {
            if let Some(checkin) = self.state_checkin_suggestion(life_model, now) {
                suggestions.push(checkin);
            }
        }

        suggestions.truncate(self.config.max_suggestions);
        suggestions
    }

    fn daily_brief_suggestion(
        &self,
        life_model: &LifeModel,
        now: chrono::DateTime<chrono::Utc>,
    ) -> ProactiveSuggestion {
        let goals_summary = if life_model.goals.daily.is_empty() {
            "你今天的好习惯可以在 Settings 中添加。".to_string()
        } else {
            let goal_names: Vec<String> = life_model
                .goals
                .daily
                .iter()
                .map(|g| g.name.clone())
                .collect();
            format!("今天的习惯：{}", goal_names.join("、"))
        };

        let prompt = format!(
            "现在是每日简报时间。请根据以下信息生成一段简短（2-3句）的个性化每日提醒：\n\n\
             用户姓名：{}\n\
             当前关注：{}\n\
             情绪状态：{}\n\
             {}\n\n\
             语气应该温暖、鼓励，引用用户的人生模型信息。",
            life_model.identity.name,
            life_model.state.current_focus,
            life_model.state.emotional_state.current_mood,
            goals_summary,
        );

        ProactiveSuggestion {
            id: format!("daily-brief-{}", now.format("%Y%m%d")),
            category: ProactiveCategory::DailyBrief,
            title: "每日简报".to_string(),
            prompt,
            priority: ProactivePriority::Medium,
            seen: false,
            created_at: now.to_rfc3339(),
        }
    }

    fn weekly_review_suggestion(
        &self,
        life_model: &LifeModel,
        now: chrono::DateTime<chrono::Utc>,
    ) -> ProactiveSuggestion {
        let short_term_goals: Vec<String> = life_model
            .goals
            .short_term
            .iter()
            .map(|g| g.name.clone())
            .collect();
        let medium_term_goals: Vec<String> = life_model
            .goals
            .medium_term
            .iter()
            .map(|g| g.name.clone())
            .collect();
        let long_term_goals: Vec<String> = life_model
            .goals
            .long_term
            .iter()
            .map(|g| g.name.clone())
            .collect();

        let prompt = format!(
            "现在是每周复盘时间。请帮助用户回顾本周并规划下周：\n\n\
             用户的核心价值观：{:?}\n\
             短期目标：{:?}\n\
             中期目标：{:?}\n\
             长期目标：{:?}\n\n\
             请从以下角度进行复盘：\n\
             1. 本周进展与成就\n\
             2. 遇到的障碍与反思\n\
             3. 对下周的建议（对齐核心价值观和目标）\n\n\
             使用 goal.read 工具查看当前目标的详细信息。",
            life_model.identity.values, short_term_goals, medium_term_goals, long_term_goals,
        );

        ProactiveSuggestion {
            id: format!("weekly-review-{}", now.format("%Y%W")),
            category: ProactiveCategory::WeeklyReview,
            title: "每周复盘".to_string(),
            prompt,
            priority: ProactivePriority::High,
            seen: false,
            created_at: now.to_rfc3339(),
        }
    }

    fn detect_stale_goals(&self, life_model: &LifeModel) -> Vec<String> {
        let now = chrono::Utc::now();
        let mut stale = Vec::new();

        for goal in &life_model.goals.short_term {
            if let Some(ref updated) = goal.updated_at {
                if let Ok(ts) = chrono::DateTime::parse_from_rfc3339(updated) {
                    let days = (now - ts.with_timezone(&chrono::Utc)).num_days();
                    if days >= self.config.stale_goal_days {
                        stale.push(format!("短期目标「{}」({}天未更新)", goal.name, days));
                    }
                }
            }
        }

        for goal in &life_model.goals.medium_term {
            if let Some(ref updated) = goal.updated_at {
                if let Ok(ts) = chrono::DateTime::parse_from_rfc3339(updated) {
                    let days = (now - ts.with_timezone(&chrono::Utc)).num_days();
                    if days >= self.config.stale_goal_days * 2 {
                        stale.push(format!("中期目标「{}」({}天未更新)", goal.name, days));
                    }
                }
            }
        }

        for goal in &life_model.goals.long_term {
            if let Some(ref updated) = goal.updated_at {
                if let Ok(ts) = chrono::DateTime::parse_from_rfc3339(updated) {
                    let days = (now - ts.with_timezone(&chrono::Utc)).num_days();
                    if days >= self.config.stale_goal_days * 3 {
                        stale.push(format!("长期目标「{}」({}天未关注)", goal.name, days));
                    }
                }
            }
        }

        stale
    }

    fn stale_goal_suggestion(
        &self,
        goal_text: &str,
        now: chrono::DateTime<chrono::Utc>,
    ) -> ProactiveSuggestion {
        let prompt = format!(
            "用户有一个目标似乎被忽略了：{}。\n\n\
             请：\n\
             1. 温和地提醒用户这个目标\n\
             2. 询问是否需要调整目标或重新规划\n\
             3. 如果目标仍然重要，建议下一步行动。\n\n\
             使用 goal.read 查看所有目标的当前状态。",
            goal_text,
        );

        ProactiveSuggestion {
            id: format!("stale-goal-{}", uuid::Uuid::new_v4()),
            category: ProactiveCategory::StaleGoal,
            title: format!("目标回顾：{}", goal_text),
            prompt,
            priority: ProactivePriority::Medium,
            seen: false,
            created_at: now.to_rfc3339(),
        }
    }

    fn proposal_reminder_suggestion(
        &self,
        pending_count: usize,
        high_risk_count: usize,
        oldest_days: Option<i64>,
        now: chrono::DateTime<chrono::Utc>,
    ) -> Option<ProactiveSuggestion> {
        let urgency = oldest_days.unwrap_or(0) >= self.config.proposal_reminder_days;

        if !urgency && high_risk_count == 0 {
            return None;
        }

        let prompt = format!(
            "你有 {} 个待处理的提案（其中 {} 个高风险），最早的已等待 {} 天。\n\n\
             请帮助用户逐个审阅这些提案，给出建议（接受/修改/拒绝）。\n\n\
             使用 proposal.list 查看待处理提案的详细信息。",
            pending_count,
            high_risk_count,
            oldest_days.unwrap_or(0),
        );

        Some(ProactiveSuggestion {
            id: format!("proposal-reminder-{}", now.format("%Y%m%d")),
            category: ProactiveCategory::PendingProposal,
            title: format!("{} 个待处理提案需要你的审阅", pending_count),
            prompt,
            priority: if high_risk_count > 0 {
                ProactivePriority::High
            } else {
                ProactivePriority::Medium
            },
            seen: false,
            created_at: now.to_rfc3339(),
        })
    }

    fn state_checkin_suggestion(
        &self,
        life_model: &LifeModel,
        now: chrono::DateTime<chrono::Utc>,
    ) -> Option<ProactiveSuggestion> {
        let last_checkin_days = life_model
            .state
            .last_updated
            .as_ref()
            .and_then(|d| {
                chrono::DateTime::parse_from_rfc3339(d)
                    .ok()
                    .map(|ts| (now - ts.with_timezone(&chrono::Utc)).num_days())
            })
            .unwrap_or(i64::MAX);

        if last_checkin_days < 1 {
            return None; // Already checked in today
        }

        let prompt = format!(
            "请做一个简短的状态检查（2-3句话）：\n\n\
             当前关注领域：{}\n\
             上次情绪状态：{}\n\n\
             请温和地询问用户：\n\
             1. 今天的感受如何？\n\
             2. 有什么需要调整的吗？\n\n\
             如果需要，使用 state.read 查看完整状态数据。",
            life_model.state.current_focus, life_model.state.emotional_state.current_mood,
        );

        Some(ProactiveSuggestion {
            id: format!("state-checkin-{}", now.format("%Y%m%d")),
            category: ProactiveCategory::StateCheckin,
            title: "状态签到".to_string(),
            prompt,
            priority: ProactivePriority::Low,
            seen: false,
            created_at: now.to_rfc3339(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_daily_brief_generated_when_enabled() {
        let engine = ProactiveEngine::default();
        let model = LifeModel::default();
        let suggestions = engine.generate_suggestions(&model, 0, 0, None);
        assert!(suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::DailyBrief));
    }

    #[test]
    fn test_weekly_review_generated() {
        let engine = ProactiveEngine::default();
        let model = LifeModel::default();
        let suggestions = engine.generate_suggestions(&model, 0, 0, None);
        assert!(suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::WeeklyReview));
    }

    #[test]
    fn test_no_proposal_reminder_when_no_proposals() {
        let engine = ProactiveEngine::default();
        let model = LifeModel::default();
        let suggestions = engine.generate_suggestions(&model, 0, 0, None);
        assert!(!suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::PendingProposal));
    }

    #[test]
    fn test_proposal_reminder_when_pending() {
        let engine = ProactiveEngine::default();
        let model = LifeModel::default();
        let suggestions = engine.generate_suggestions(&model, 3, 1, Some(4));
        assert!(suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::PendingProposal));
    }

    #[test]
    fn test_max_suggestions_truncated() {
        let config = ProactiveConfig {
            max_suggestions: 2,
            ..Default::default()
        };
        let engine = ProactiveEngine::new(config);
        let model = LifeModel::default();
        let suggestions = engine.generate_suggestions(&model, 3, 1, Some(5));
        assert!(suggestions.len() <= 2);
    }

    #[test]
    fn test_disabled_categories_excluded() {
        let config = ProactiveConfig {
            enable_daily_brief: false,
            enable_weekly_review: false,
            enable_state_checkin: false,
            ..Default::default()
        };
        let engine = ProactiveEngine::new(config);
        let model = LifeModel::default();
        let suggestions = engine.generate_suggestions(&model, 0, 0, None);
        assert!(!suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::DailyBrief));
        assert!(!suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::WeeklyReview));
    }
}
