//! Proactive check-in engine: generates suggestions for daily briefs,
//! weekly reviews, stale goal reminders, pending proposal alerts,
//! and state check-in prompts. All outputs are declarative suggestions
//! — actual execution is handled by the canonical Work runtime in the Tauri shell.

use crate::agent::evidence_store::{
    EvidenceDraft, EvidencePrivacyLevel, EvidenceQuery, EvidenceRecord, EvidenceSourceRef,
    EvidenceSourceType, EvidenceStatus, EvidenceStore, EvidenceType,
};
use crate::agent::types::{AgentProposal, ProposalSource, ProposalStatus, RiskLevel};
use anyhow::Result;
use ring::digest::{digest, SHA256};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

const NEGATIVE_REMINDER_INITIAL_CONFIDENCE: f32 = 0.65;
const NEGATIVE_REMINDER_EFFECT_THRESHOLD: f32 = 0.4;
const REMINDER_EVIDENCE_PREFIX: &str = "proactive.reminder.";
const MAX_PROACTIVE_DAILY_TASKS: usize = 8;
const MAX_PROACTIVE_DAILY_TASK_CHARS: usize = 2_048;
const MAX_PROACTIVE_VALUES: usize = 8;
const MAX_PROACTIVE_VALUE_CHARS: usize = 2_048;
const MAX_PROACTIVE_LONG_TERM_GOALS: usize = 8;
const MAX_PROACTIVE_LONG_TERM_GOAL_CHARS: usize = 4_096;

/// Bounded read model assembled by the Tauri product owner from canonical
/// LifeModel v2 and StateStore. Proactive suggestions never load legacy YAML
/// and never gain authority to mutate either source.
#[derive(Debug, Clone, Default)]
pub struct ProactivePersonalContext {
    daily_tasks: Vec<String>,
    values: Vec<String>,
    long_term_goals: Vec<ProactiveLongTermGoal>,
    latest_state_observation_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone)]
pub struct ProactiveLongTermGoal {
    pub direction: String,
    pub confirmed_at: chrono::DateTime<chrono::Utc>,
}

impl ProactivePersonalContext {
    pub fn bounded(
        daily_tasks: Vec<String>,
        values: Vec<String>,
        long_term_goals: Vec<ProactiveLongTermGoal>,
        latest_state_observation_at: Option<chrono::DateTime<chrono::Utc>>,
    ) -> Self {
        Self {
            daily_tasks: bounded_texts(
                daily_tasks,
                MAX_PROACTIVE_DAILY_TASKS,
                MAX_PROACTIVE_DAILY_TASK_CHARS,
            ),
            values: bounded_texts(values, MAX_PROACTIVE_VALUES, MAX_PROACTIVE_VALUE_CHARS),
            long_term_goals: bounded_goals(
                long_term_goals,
                MAX_PROACTIVE_LONG_TERM_GOALS,
                MAX_PROACTIVE_LONG_TERM_GOAL_CHARS,
            ),
            latest_state_observation_at,
        }
    }
}

fn bounded_texts(values: Vec<String>, max_items: usize, max_chars: usize) -> Vec<String> {
    let mut selected = Vec::new();
    let mut used_chars = 0usize;
    for value in values {
        let value_chars = value.chars().count();
        if value_chars == 0 || value_chars > max_chars.saturating_sub(used_chars) {
            continue;
        }
        selected.push(value);
        used_chars += value_chars;
        if selected.len() == max_items || used_chars == max_chars {
            break;
        }
    }
    selected
}

fn bounded_goals(
    goals: Vec<ProactiveLongTermGoal>,
    max_items: usize,
    max_chars: usize,
) -> Vec<ProactiveLongTermGoal> {
    let mut selected = Vec::new();
    let mut used_chars = 0usize;
    for goal in goals {
        let goal_chars = goal.direction.chars().count();
        if goal_chars == 0 || goal_chars > max_chars.saturating_sub(used_chars) {
            continue;
        }
        selected.push(goal);
        used_chars += goal_chars;
        if selected.len() == max_items || used_chars == max_chars {
            break;
        }
    }
    selected
}

/// A proactive suggestion generated by the check-in engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProactiveSuggestion {
    pub id: String,
    pub category: ProactiveCategory,
    pub title: String,
    pub prompt: String,
    pub priority: ProactivePriority,
    /// Whether the user has seen this suggestion
    pub seen: bool,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum ProactiveCategory {
    DailyBrief,
    WeeklyReview,
    StaleGoal,
    PendingProposal,
    StateCheckin,
}

impl std::fmt::Display for ProactiveCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProactiveCategory::DailyBrief => write!(f, "daily_brief"),
            ProactiveCategory::WeeklyReview => write!(f, "weekly_review"),
            ProactiveCategory::StaleGoal => write!(f, "stale_goal"),
            ProactiveCategory::PendingProposal => write!(f, "pending_proposal"),
            ProactiveCategory::StateCheckin => write!(f, "state_checkin"),
        }
    }
}

impl ProactiveCategory {
    fn from_storage_key(value: &str) -> Option<Self> {
        match value {
            "daily_brief" => Some(ProactiveCategory::DailyBrief),
            "weekly_review" => Some(ProactiveCategory::WeeklyReview),
            "stale_goal" => Some(ProactiveCategory::StaleGoal),
            "pending_proposal" => Some(ProactiveCategory::PendingProposal),
            "state_checkin" => Some(ProactiveCategory::StateCheckin),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProactivePriority {
    Low,
    Medium,
    High,
}

impl std::fmt::Display for ProactivePriority {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProactivePriority::Low => write!(f, "low"),
            ProactivePriority::Medium => write!(f, "medium"),
            ProactivePriority::High => write!(f, "high"),
        }
    }
}

/// Configuration for the proactive engine.
pub struct ProactiveConfig {
    /// Days before a goal is considered stale (no progress update)
    pub stale_goal_days: i64,
    /// Days before a pending proposal triggers a reminder
    pub proposal_reminder_days: i64,
    /// Whether daily brief is enabled
    pub enable_daily_brief: bool,
    /// Whether weekly review is enabled
    pub enable_weekly_review: bool,
    /// Whether state check-in is enabled
    pub enable_state_checkin: bool,
    /// Maximum suggestions per check-in round
    pub max_suggestions: usize,
}

impl Default for ProactiveConfig {
    fn default() -> Self {
        Self {
            stale_goal_days: 7,
            proposal_reminder_days: 3,
            enable_daily_brief: true,
            enable_weekly_review: true,
            enable_state_checkin: true,
            max_suggestions: 5,
        }
    }
}

/// Engine that generates declarative suggestions from bounded product facts.
#[derive(Default)]
pub struct ProactiveEngine {
    config: ProactiveConfig,
}

impl ProactiveEngine {
    pub fn new(config: ProactiveConfig) -> Self {
        Self { config }
    }

    /// Generate all proactive suggestions for the current bounded product facts.
    pub fn generate_suggestions(
        &self,
        context: &ProactivePersonalContext,
        pending_proposal_count: usize,
        high_risk_proposal_count: usize,
        oldest_proposal_days: Option<i64>,
    ) -> Vec<ProactiveSuggestion> {
        let mut suggestions = Vec::new();
        let now = chrono::Utc::now();

        // Daily brief
        if self.config.enable_daily_brief {
            suggestions.push(self.daily_brief_suggestion(context, now));
        }

        // Weekly review (only on Mondays or if never done)
        if self.config.enable_weekly_review {
            suggestions.push(self.weekly_review_suggestion(context, now));
        }

        // Stale goal detection
        for goal_text in self.detect_stale_goals(context) {
            suggestions.push(self.stale_goal_suggestion(&goal_text, now));
        }

        // Pending proposal reminder
        if pending_proposal_count > 0 {
            if let Some(reminder) = self.proposal_reminder_suggestion(
                pending_proposal_count,
                high_risk_proposal_count,
                oldest_proposal_days,
                now,
            ) {
                suggestions.push(reminder);
            }
        }

        // State check-in (if last recorded state is old)
        if self.config.enable_state_checkin {
            if let Some(checkin) = self.state_checkin_suggestion(context, now) {
                suggestions.push(checkin);
            }
        }

        suggestions.truncate(self.config.max_suggestions);
        suggestions
    }

    /// Generate suggestions while consulting negative reminder evidence.
    ///
    /// The initial effect is deliberately narrow: a rejected reminder lowers the
    /// priority of future reminders in the same proactive category. It does not
    /// suppress all proactive help or persist a stable preference.
    pub fn generate_suggestions_with_evidence(
        &self,
        context: &ProactivePersonalContext,
        pending_proposal_count: usize,
        high_risk_proposal_count: usize,
        oldest_proposal_days: Option<i64>,
        evidence_store: &EvidenceStore,
    ) -> Vec<ProactiveSuggestion> {
        let mut suggestions = self.generate_suggestions(
            context,
            pending_proposal_count,
            high_risk_proposal_count,
            oldest_proposal_days,
        );
        self.apply_negative_reminder_evidence(&mut suggestions, evidence_store);
        suggestions
    }

    pub fn record_rejected_reminder_proposal(
        &self,
        evidence_store: &EvidenceStore,
        proposal: &AgentProposal,
    ) -> Result<Option<EvidenceRecord>> {
        if proposal.status != ProposalStatus::Rejected
            || proposal.source != ProposalSource::ProactiveAgent
        {
            return Ok(None);
        }
        let Some(category) = reminder_category_from_proposal(proposal) else {
            return Ok(None);
        };

        let affected_path = reminder_affected_path(&category);
        let payload = serde_json::json!({
            "proposal_id": proposal.id,
            "run_id": proposal.run_id,
            "status": proposal.status.to_string(),
            "category": category.to_string(),
            "affected_path": affected_path,
        });
        let payload_text = payload.to_string();

        let mut draft = EvidenceDraft::new(
            EvidenceType::RuntimeBehavior,
            affected_path,
            NEGATIVE_REMINDER_INITIAL_CONFIDENCE,
            RiskLevel::Low,
            EvidencePrivacyLevel::Internal,
        )
        .with_summary(format!(
            "Rejected proactive {} reminder; weaken similar future reminders",
            category
        ))
        .with_source_ref(EvidenceSourceRef::from_payload(
            EvidenceSourceType::Proposal,
            &proposal.id,
            proposal.source_detail.as_deref(),
            &payload_text,
        ))
        .with_linked_proposal(proposal.id.clone());

        if let Some(run_id) = proposal.run_id.as_deref() {
            draft = draft
                .with_source_ref(EvidenceSourceRef::from_payload(
                    EvidenceSourceType::WorkRun,
                    run_id,
                    Some("proactive_reminder_run"),
                    &payload_text,
                ))
                .with_linked_work_run(run_id.to_string());
        }

        if let Some(action_id) = proposal
            .after
            .get("source_action_id")
            .and_then(serde_json::Value::as_str)
        {
            draft = draft.with_source_ref(EvidenceSourceRef::from_payload(
                EvidenceSourceType::RunMetadata,
                action_id,
                Some("proactive_reminder_action"),
                &payload_text,
            ));
        }

        draft.run_metadata = serde_json::json!({
            "polarity": "negative",
            "behavior": "proactive_reminder_rejected",
            "reminder_category": category.to_string(),
            "similarity_key_digest": sha256_hex(category.to_string().as_bytes()),
            "effect": "weaken_similar_future_reminders",
        });

        Ok(Some(evidence_store.create_evidence(draft)?))
    }

    fn apply_negative_reminder_evidence(
        &self,
        suggestions: &mut [ProactiveSuggestion],
        evidence_store: &EvidenceStore,
    ) {
        let evidence = evidence_store
            .query(EvidenceQuery {
                evidence_type: Some(EvidenceType::RuntimeBehavior),
                limit: Some(100),
                ..Default::default()
            })
            .unwrap_or_default();
        let mut negative_categories: HashMap<ProactiveCategory, f32> = HashMap::new();

        for record in evidence.iter().filter(|record| {
            matches!(
                record.status,
                EvidenceStatus::Candidate | EvidenceStatus::Active | EvidenceStatus::Weakened
            ) && record.confidence >= NEGATIVE_REMINDER_EFFECT_THRESHOLD
                && record
                    .run_metadata
                    .get("behavior")
                    .and_then(serde_json::Value::as_str)
                    == Some("proactive_reminder_rejected")
        }) {
            if let Some(category) = reminder_category_from_evidence(record) {
                negative_categories
                    .entry(category)
                    .and_modify(|confidence| *confidence = confidence.max(record.confidence))
                    .or_insert(record.confidence);
            }
        }

        for suggestion in suggestions {
            if negative_categories.contains_key(&suggestion.category) {
                suggestion.priority = weaken_priority(&suggestion.priority);
            }
        }
    }

    fn daily_brief_suggestion(
        &self,
        context: &ProactivePersonalContext,
        now: chrono::DateTime<chrono::Utc>,
    ) -> ProactiveSuggestion {
        let tasks_summary = if context.daily_tasks.is_empty() {
            "今天还没有已确认的任务。".to_string()
        } else {
            format!("今天的任务：{}", context.daily_tasks.join("、"))
        };

        let prompt = format!(
            "现在是每日简报时间。请根据以下信息生成一段简短（2-3句）的个性化每日提醒：\n\n\
             {}\n\n\
             语气应该温暖、简短；只使用上述已确认任务，不推断用户状态。",
            tasks_summary,
        );

        ProactiveSuggestion {
            id: format!("daily-brief-{}", now.format("%Y%m%d")),
            category: ProactiveCategory::DailyBrief,
            title: "每日简报".to_string(),
            prompt,
            priority: ProactivePriority::Medium,
            seen: false,
            created_at: now.to_rfc3339(),
        }
    }

    fn weekly_review_suggestion(
        &self,
        context: &ProactivePersonalContext,
        now: chrono::DateTime<chrono::Utc>,
    ) -> ProactiveSuggestion {
        let long_term_goals = context
            .long_term_goals
            .iter()
            .map(|goal| goal.direction.clone())
            .collect::<Vec<_>>();

        let prompt = format!(
            "现在是每周复盘时间。请帮助用户回顾本周并规划下周：\n\n\
             用户确认的长期价值观：{:?}\n\
             长期目标：{:?}\n\n\
             请从以下角度进行复盘：\n\
             1. 本周进展与成就\n\
             2. 遇到的障碍与反思\n\
             3. 对下周的建议（对齐核心价值观和目标）\n\n\
             只使用上述已确认的长期信息；任务进展需要从当前对话或 Agent Memory 获取。",
            context.values, long_term_goals,
        );

        ProactiveSuggestion {
            id: format!("weekly-review-{}", now.format("%Y%W")),
            category: ProactiveCategory::WeeklyReview,
            title: "每周复盘".to_string(),
            prompt,
            priority: ProactivePriority::High,
            seen: false,
            created_at: now.to_rfc3339(),
        }
    }

    fn detect_stale_goals(&self, context: &ProactivePersonalContext) -> Vec<String> {
        let now = chrono::Utc::now();
        let mut stale = Vec::new();

        for goal in &context.long_term_goals {
            let days = (now - goal.confirmed_at).num_days();
            if days >= self.config.stale_goal_days * 3 {
                stale.push(format!(
                    "长期目标「{}」({}天未确认更新)",
                    goal.direction, days
                ));
            }
        }

        stale
    }

    fn stale_goal_suggestion(
        &self,
        goal_text: &str,
        now: chrono::DateTime<chrono::Utc>,
    ) -> ProactiveSuggestion {
        let prompt = format!(
            "用户有一个目标似乎被忽略了：{}。\n\n\
             请：\n\
             1. 温和地提醒用户这个目标\n\
             2. 询问是否需要调整目标或重新规划\n\
             3. 如果目标仍然重要，建议下一步行动。\n\n\
             只基于这条已确认的长期目标和当前对话，不假设任务进度。",
            goal_text,
        );

        ProactiveSuggestion {
            id: format!("stale-goal-{}", uuid::Uuid::new_v4()),
            category: ProactiveCategory::StaleGoal,
            title: format!("目标回顾：{}", goal_text),
            prompt,
            priority: ProactivePriority::Medium,
            seen: false,
            created_at: now.to_rfc3339(),
        }
    }

    fn proposal_reminder_suggestion(
        &self,
        pending_count: usize,
        high_risk_count: usize,
        oldest_days: Option<i64>,
        now: chrono::DateTime<chrono::Utc>,
    ) -> Option<ProactiveSuggestion> {
        let urgency = oldest_days.unwrap_or(0) >= self.config.proposal_reminder_days;

        if !urgency && high_risk_count == 0 {
            return None;
        }

        let prompt = format!(
            "你有 {} 个待处理的提案（其中 {} 个高风险），最早的已等待 {} 天。\n\n\
             请帮助用户逐个审阅这些提案，给出建议（接受/修改/拒绝）。\n\n\
             使用 proposal.list 查看待处理提案的详细信息。",
            pending_count,
            high_risk_count,
            oldest_days.unwrap_or(0),
        );

        Some(ProactiveSuggestion {
            id: format!("proposal-reminder-{}", now.format("%Y%m%d")),
            category: ProactiveCategory::PendingProposal,
            title: format!("{} 个待处理提案需要你的审阅", pending_count),
            prompt,
            priority: if high_risk_count > 0 {
                ProactivePriority::High
            } else {
                ProactivePriority::Medium
            },
            seen: false,
            created_at: now.to_rfc3339(),
        })
    }

    fn state_checkin_suggestion(
        &self,
        context: &ProactivePersonalContext,
        now: chrono::DateTime<chrono::Utc>,
    ) -> Option<ProactiveSuggestion> {
        let last_checkin_days = context
            .latest_state_observation_at
            .map(|timestamp| (now - timestamp).num_days())
            .unwrap_or(i64::MAX);

        if last_checkin_days < 1 {
            return None; // Already checked in today
        }

        let prompt = "请做一个简短的状态检查（2-3句话）：\n\n\
             请温和地询问用户：\n\
             1. 今天的感受如何？\n\
             2. 有什么需要调整的吗？\n\n\
             如果需要，使用 state.read 查看当前结构化状态；不要从缺失数据推断情绪。"
            .to_string();

        Some(ProactiveSuggestion {
            id: format!("state-checkin-{}", now.format("%Y%m%d")),
            category: ProactiveCategory::StateCheckin,
            title: "状态签到".to_string(),
            prompt,
            priority: ProactivePriority::Low,
            seen: false,
            created_at: now.to_rfc3339(),
        })
    }
}

fn reminder_affected_path(category: &ProactiveCategory) -> String {
    format!("{}{}", REMINDER_EVIDENCE_PREFIX, category)
}

fn reminder_category_from_proposal(proposal: &AgentProposal) -> Option<ProactiveCategory> {
    proposal
        .after
        .get("proactive_reminder_category")
        .or_else(|| proposal.after.pointer("/proactive_reminder/category"))
        .and_then(serde_json::Value::as_str)
        .and_then(ProactiveCategory::from_storage_key)
        .or_else(|| {
            proposal
                .affected_path
                .strip_prefix(REMINDER_EVIDENCE_PREFIX)
                .and_then(ProactiveCategory::from_storage_key)
        })
}

fn reminder_category_from_evidence(record: &EvidenceRecord) -> Option<ProactiveCategory> {
    record
        .run_metadata
        .get("reminder_category")
        .and_then(serde_json::Value::as_str)
        .and_then(ProactiveCategory::from_storage_key)
        .or_else(|| {
            record
                .affected_path
                .strip_prefix(REMINDER_EVIDENCE_PREFIX)
                .and_then(ProactiveCategory::from_storage_key)
        })
}

fn weaken_priority(priority: &ProactivePriority) -> ProactivePriority {
    match priority {
        ProactivePriority::High | ProactivePriority::Medium => ProactivePriority::Low,
        ProactivePriority::Low => ProactivePriority::Low,
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let hash = digest(&SHA256, bytes);
    let bytes = hash.as_ref();
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push_str(&format!("{:02x}", b));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::evidence_store::{
        EvidenceQuery, EvidenceSourceType, EvidenceStatus, EvidenceStore, EvidenceType,
    };
    use crate::agent::types::{AgentProposal, ProposalSource, ProposalType, RiskLevel};

    fn rejected_pending_proposal() -> AgentProposal {
        let mut proposal = AgentProposal::new(
            ProposalType::ScheduledTask,
            "proactive.reminder.pending_proposal",
            serde_json::json!({
                "proactive_reminder_category": "pending_proposal",
                "reminder_id": "proposal-reminder-test",
                "prompt_digest": "digest-only-no-raw-prompt",
            }),
            "raw rejected reminder text should not be copied into evidence",
            0.65,
            RiskLevel::Low,
            ProposalSource::ProactiveAgent,
        );
        proposal.run_id = Some("run-reminder-1".into());
        proposal.reject();
        proposal
    }

    #[test]
    fn test_daily_brief_generated_when_enabled() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::default();
        let suggestions = engine.generate_suggestions(&context, 0, 0, None);
        assert!(suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::DailyBrief));
    }

    #[test]
    fn test_weekly_review_generated() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::default();
        let suggestions = engine.generate_suggestions(&context, 0, 0, None);
        assert!(suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::WeeklyReview));
    }

    #[test]
    fn proactive_prompts_use_only_bounded_canonical_facts() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::bounded(
            vec!["完成设计评审".into()],
            vec!["诚实".into()],
            vec![ProactiveLongTermGoal {
                direction: "建立可持续的工作节奏".into(),
                confirmed_at: chrono::Utc::now() - chrono::Duration::days(30),
            }],
            None,
        );

        let suggestions = engine.generate_suggestions(&context, 0, 0, None);
        assert!(suggestions
            .iter()
            .all(|suggestion| !suggestion.prompt.contains("goal.read")));
        let daily = suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::DailyBrief)
            .unwrap();
        assert!(daily.prompt.contains("完成设计评审"));
        let weekly = suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::WeeklyReview)
            .unwrap();
        assert!(weekly.prompt.contains("诚实"));
        assert!(weekly.prompt.contains("建立可持续的工作节奏"));
        let checkin = suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::StateCheckin)
            .unwrap();
        assert!(!checkin.prompt.contains("情绪状态："));
        assert!(checkin.prompt.contains("不要从缺失数据推断情绪"));
    }

    #[test]
    fn proactive_personal_context_enforces_item_and_character_budgets() {
        let oversized = "x".repeat(MAX_PROACTIVE_DAILY_TASK_CHARS + 1);
        let tasks = std::iter::once(oversized)
            .chain((0..32).map(|index| format!("task-{index}")))
            .collect();
        let values = (0..32).map(|index| format!("value-{index}")).collect();
        let goals = (0..32)
            .map(|index| ProactiveLongTermGoal {
                direction: format!("goal-{index}"),
                confirmed_at: chrono::Utc::now(),
            })
            .collect();

        let context = ProactivePersonalContext::bounded(tasks, values, goals, None);

        assert_eq!(context.daily_tasks.len(), MAX_PROACTIVE_DAILY_TASKS);
        assert_eq!(context.values.len(), MAX_PROACTIVE_VALUES);
        assert_eq!(context.long_term_goals.len(), MAX_PROACTIVE_LONG_TERM_GOALS);
        assert!(
            context
                .daily_tasks
                .iter()
                .map(|task| task.chars().count())
                .sum::<usize>()
                <= MAX_PROACTIVE_DAILY_TASK_CHARS
        );
    }

    #[test]
    fn test_no_proposal_reminder_when_no_proposals() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::default();
        let suggestions = engine.generate_suggestions(&context, 0, 0, None);
        assert!(!suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::PendingProposal));
    }

    #[test]
    fn test_proposal_reminder_when_pending() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::default();
        let suggestions = engine.generate_suggestions(&context, 3, 1, Some(4));
        assert!(suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::PendingProposal));
    }

    #[test]
    fn test_max_suggestions_truncated() {
        let config = ProactiveConfig {
            max_suggestions: 2,
            ..Default::default()
        };
        let engine = ProactiveEngine::new(config);
        let context = ProactivePersonalContext::default();
        let suggestions = engine.generate_suggestions(&context, 3, 1, Some(5));
        assert!(suggestions.len() <= 2);
    }

    #[test]
    fn test_disabled_categories_excluded() {
        let config = ProactiveConfig {
            enable_daily_brief: false,
            enable_weekly_review: false,
            enable_state_checkin: false,
            ..Default::default()
        };
        let engine = ProactiveEngine::new(config);
        let context = ProactivePersonalContext::default();
        let suggestions = engine.generate_suggestions(&context, 0, 0, None);
        assert!(!suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::DailyBrief));
        assert!(!suggestions
            .iter()
            .any(|s| s.category == ProactiveCategory::WeeklyReview));
    }

    #[test]
    fn rejected_reminder_proposal_creates_negative_evidence_with_source_refs() {
        let engine = ProactiveEngine::default();
        let evidence_store = EvidenceStore::new_in_memory().unwrap();
        let proposal = rejected_pending_proposal();

        let evidence = engine
            .record_rejected_reminder_proposal(&evidence_store, &proposal)
            .unwrap()
            .unwrap();

        assert_eq!(evidence.evidence_type, EvidenceType::RuntimeBehavior);
        assert_eq!(evidence.status, EvidenceStatus::Candidate);
        assert_eq!(
            evidence.affected_path,
            "proactive.reminder.pending_proposal"
        );
        assert!(evidence.linked_proposal_ids.contains(&proposal.id));
        assert!(evidence
            .linked_work_run_ids
            .contains(&"run-reminder-1".to_string()));
        assert!(evidence
            .source_refs
            .iter()
            .any(|source| source.source_type == EvidenceSourceType::Proposal));
        assert!(evidence
            .source_refs
            .iter()
            .any(|source| source.source_type == EvidenceSourceType::WorkRun));

        let serialized = serde_json::to_string(&evidence).unwrap();
        assert!(!serialized.contains("raw rejected reminder text"));
    }

    #[test]
    fn negative_reminder_evidence_weakens_similar_but_not_unrelated_reminders() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::default();
        let evidence_store = EvidenceStore::new_in_memory().unwrap();
        let proposal = rejected_pending_proposal();
        engine
            .record_rejected_reminder_proposal(&evidence_store, &proposal)
            .unwrap();

        let suggestions =
            engine.generate_suggestions_with_evidence(&context, 3, 0, Some(4), &evidence_store);
        let pending = suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::PendingProposal)
            .unwrap();
        assert_eq!(pending.priority, ProactivePriority::Low);

        let daily = suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::DailyBrief)
            .unwrap();
        assert_eq!(daily.priority, ProactivePriority::Medium);
    }

    #[test]
    fn weakening_or_archiving_negative_evidence_removes_reminder_effect() {
        let engine = ProactiveEngine::default();
        let context = ProactivePersonalContext::default();
        let evidence_store = EvidenceStore::new_in_memory().unwrap();

        let proposal = rejected_pending_proposal();
        let evidence = engine
            .record_rejected_reminder_proposal(&evidence_store, &proposal)
            .unwrap()
            .unwrap();
        evidence_store
            .weaken_evidence(&evidence.id, 0.4, Some("user restored reminder"))
            .unwrap();
        let weakened_suggestions =
            engine.generate_suggestions_with_evidence(&context, 3, 0, Some(4), &evidence_store);
        let pending = weakened_suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::PendingProposal)
            .unwrap();
        assert_eq!(pending.priority, ProactivePriority::Medium);

        let second = engine
            .record_rejected_reminder_proposal(&evidence_store, &rejected_pending_proposal())
            .unwrap()
            .unwrap();
        evidence_store
            .archive_evidence(&second.id, Some("forget rejected reminder signal"))
            .unwrap();
        let active_records = evidence_store
            .query(EvidenceQuery {
                evidence_type: Some(EvidenceType::RuntimeBehavior),
                status: Some(EvidenceStatus::Archived),
                ..Default::default()
            })
            .unwrap();
        assert_eq!(active_records.len(), 1);

        let archived_suggestions =
            engine.generate_suggestions_with_evidence(&context, 3, 0, Some(4), &evidence_store);
        let pending = archived_suggestions
            .iter()
            .find(|suggestion| suggestion.category == ProactiveCategory::PendingProposal)
            .unwrap();
        assert_eq!(pending.priority, ProactivePriority::Medium);
    }
}
