use crate::agent::AgentExecutionBudget;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// JSON envelope that all skills must output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillJsonEnvelope {
    pub summary: String,
    pub structured_output: Value,
    pub proposal_candidates: Vec<SkillProposalCandidate>,
    #[serde(default)]
    pub warnings: Vec<String>,
}

/// A proposal candidate generated by a skill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillProposalCandidate {
    pub proposal_type: String,
    pub affected_path: String,
    pub after: Value,
    pub reason: String,
    #[serde(default)]
    pub confidence: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillManifest {
    pub id: String,
    pub name: String,
    pub description: String,
    pub required_context: Vec<String>,
    pub allowed_tools: Vec<String>,
    pub execution_budget: AgentExecutionBudget,
    pub input_schema: Value,
    pub output_schema: Value,
    pub proposal_policy: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillRunResult {
    pub skill_id: String,
    pub summary: String,
    pub structured_output: Value,
    pub proposal_candidates: Vec<SkillProposalCandidate>,
    pub warnings: Vec<String>,
    pub parse_error: Option<String>,
}

pub struct SkillRegistry {
    manifests: HashMap<String, SkillManifest>,
}

impl SkillRegistry {
    pub fn built_in() -> Self {
        let mut registry = Self {
            manifests: HashMap::new(),
        };
        registry.register(Self::weekly_review());
        registry.register(Self::goal_breakdown());
        registry.register(Self::memory_consolidation());
        registry
    }

    pub fn register(&mut self, manifest: SkillManifest) {
        self.manifests.insert(manifest.id.clone(), manifest);
    }

    pub fn list(&self) -> Vec<SkillManifest> {
        let mut skills: Vec<_> = self.manifests.values().cloned().collect();
        skills.sort_by(|a, b| a.id.cmp(&b.id));
        skills
    }

    pub fn get(&self, id: &str) -> Option<SkillManifest> {
        self.manifests.get(id).cloned()
    }

    pub fn remove(&mut self, id: &str) {
        self.manifests.remove(id);
    }

    pub fn remove_by_source_prefix(&mut self, prefix: &str) {
        self.manifests.retain(|id, _| !id.starts_with(prefix));
    }

    /// Build the system prompt for a skill.
    /// This is the prompt that tells the model how to act as this skill.
    pub fn build_system_prompt(&self, id: &str) -> anyhow::Result<String> {
        let manifest = self
            .manifests
            .get(id)
            .ok_or_else(|| anyhow::anyhow!("unknown skill: {}", id))?;

        let base_prompt = format!(
            "你是 OpenLife 的 {} 助手。\n\n{}",
            manifest.name, manifest.description
        );

        let output_instruction = r#"
你必须严格输出以下 JSON envelope 格式（不要包含 markdown 代码块标记）：

{
  "summary": "简短摘要（1-2 句话）",
  "structured_output": {
    // 技能特定的结构化输出
  },
  "proposal_candidates": [
    {
      "proposal_type": "goal_update|state_update|memory_write|memory_archive",
      "affected_path": "具体路径",
      "after": {
        // 新值
      },
      "reason": "为什么建议这个变更",
      "confidence": 0.8
    }
  ],
  "warnings": []
}

重要规则：
- 只输出纯 JSON，不要添加 ```json 标记
- proposal_candidates 可以为空数组 []
- 如果没有任何建议变更，proposal_candidates 应为 []
- confidence 范围 0.0-1.0
"#;

        Ok(format!("{}\n{}", base_prompt, output_instruction))
    }

    /// Build the full skill prompt with context.
    pub fn build_skill_prompt(
        &self,
        id: &str,
        input: &Value,
        _context: &SkillContext,
    ) -> anyhow::Result<String> {
        let manifest = self
            .manifests
            .get(id)
            .ok_or_else(|| anyhow::anyhow!("unknown skill: {}", id))?;

        let user_input = input
            .get("text")
            .and_then(Value::as_str)
            .unwrap_or("")
            .trim();

        let prompt = format!(
            "[Skill: {}]\n用户输入: {}\n\n请基于你的技能能力生成回复。",
            manifest.name,
            if user_input.is_empty() {
                "（无具体输入）"
            } else {
                user_input
            }
        );

        Ok(prompt)
    }

    fn weekly_review() -> SkillManifest {
        SkillManifest {
            id: "weekly_review".into(),
            name: "Weekly Review".into(),
            description: "汇总近期 AgentRun、目标、状态和记忆，生成周复盘与改进建议。".into(),
            required_context: vec![
                "agent_runs".into(),
                "goals".into(),
                "state".into(),
                "memory".into(),
            ],
            allowed_tools: vec![],
            execution_budget: AgentExecutionBudget::default(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "text": {"type": "string", "description": "用户的额外输入或要求"}
                }
            }),
            output_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "structured_output": {"type": "object"},
                    "proposal_candidates": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "proposal_type": {"type": "string", "enum": ["state_update", "goal_update"]},
                                "affected_path": {"type": "string"},
                                "after": {"type": "object"},
                                "reason": {"type": "string"},
                                "confidence": {"type": "number"}
                            }
                        }
                    },
                    "warnings": {"type": "array", "items": {"type": "string"}}
                }
            }),
            proposal_policy: "review_required".into(),
        }
    }

    fn goal_breakdown() -> SkillManifest {
        SkillManifest {
            id: "goal_breakdown".into(),
            name: "Goal Breakdown".into(),
            description: "将长期目标拆解为里程碑、每日行动和风险提示。".into(),
            required_context: vec!["life_model.goals".into(), "state".into()],
            allowed_tools: vec![],
            execution_budget: AgentExecutionBudget::default(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "text": {"type": "string", "description": "用户输入的目标描述"}
                }
            }),
            output_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "structured_output": {"type": "object"},
                    "proposal_candidates": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "proposal_type": {"type": "string", "enum": ["goal_update"]},
                                "affected_path": {"type": "string"},
                                "after": {"type": "object"},
                                "reason": {"type": "string"},
                                "confidence": {"type": "number"}
                            }
                        }
                    },
                    "warnings": {"type": "array", "items": {"type": "string"}}
                }
            }),
            proposal_policy: "review_required".into(),
        }
    }

    fn memory_consolidation() -> SkillManifest {
        SkillManifest {
            id: "memory_consolidation".into(),
            name: "Memory Consolidation".into(),
            description: "从近期聊天和记忆中生成长期记忆候选与归档建议。".into(),
            required_context: vec!["memory".into(), "chat_history".into()],
            allowed_tools: vec![],
            execution_budget: AgentExecutionBudget::default(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "text": {"type": "string", "description": "用户的额外要求"}
                }
            }),
            output_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "structured_output": {"type": "object"},
                    "proposal_candidates": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "proposal_type": {"type": "string", "enum": ["memory_write", "memory_archive"]},
                                "affected_path": {"type": "string"},
                                "after": {"type": "object"},
                                "reason": {"type": "string"},
                                "confidence": {"type": "number"}
                            }
                        }
                    },
                    "warnings": {"type": "array", "items": {"type": "string"}}
                }
            }),
            proposal_policy: "review_required".into(),
        }
    }
}

/// Context available to a skill during execution.
#[derive(Debug, Clone, Default)]
pub struct SkillContext {
    pub life_model_json: Option<String>,
    pub recent_runs_json: Option<String>,
    pub recent_memory_json: Option<String>,
    pub chat_history_json: Option<String>,
}

/// Parse skill JSON output with fallback strategies.
///
/// Strategy 1: Strict JSON parsing
/// Strategy 2: Extract JSON from fenced code block
/// Strategy 3: Return error
pub fn parse_skill_json(text: &str) -> Result<SkillJsonEnvelope, String> {
    // Strategy 1: Direct parse
    if let Ok(envelope) = serde_json::from_str::<SkillJsonEnvelope>(text) {
        return Ok(envelope);
    }

    // Strategy 2: Extract from fenced code block
    if let Some(json_str) = extract_json_from_fenced_block(text) {
        if let Ok(envelope) = serde_json::from_str::<SkillJsonEnvelope>(json_str) {
            return Ok(envelope);
        }
    }

    // Strategy 3: Try to find the first JSON object in the text
    if let Some(json_str) = extract_first_json_object(text) {
        if let Ok(envelope) = serde_json::from_str::<SkillJsonEnvelope>(json_str) {
            return Ok(envelope);
        }
    }

    Err("无法解析技能输出为有效的 JSON envelope。模型输出格式不符合要求。".to_string())
}

fn extract_json_from_fenced_block(text: &str) -> Option<&str> {
    let start = text.find("```json")? + 7;
    let end = text[start..].find("```")?;
    Some(text[start..start + end].trim())
}

fn extract_first_json_object(text: &str) -> Option<&str> {
    let start = text.find('{')?;
    let mut depth = 0;
    let mut in_string = false;
    let mut escape = false;

    for (idx, b) in text[start..].bytes().enumerate() {
        if escape {
            escape = false;
            continue;
        }
        if in_string {
            if b == b'\\' {
                escape = true;
                continue;
            }
            if b == b'"' {
                in_string = false;
            }
            continue;
        }
        if b == b'"' {
            in_string = true;
            continue;
        }
        if b == b'{' {
            depth += 1;
        } else if b == b'}' {
            depth -= 1;
            if depth == 0 {
                return Some(&text[start..=start + idx]);
            }
        }
    }
    None
}

impl Default for SkillRegistry {
    fn default() -> Self {
        Self::built_in()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_builtin_skills_registered() {
        let registry = SkillRegistry::built_in();
        let skills = registry.list();
        assert_eq!(skills.len(), 3);
        assert!(registry.get("weekly_review").is_some());
        assert!(registry.get("goal_breakdown").is_some());
        assert!(registry.get("memory_consolidation").is_some());
    }

    #[test]
    fn test_build_system_prompt_weekly_review() {
        let registry = SkillRegistry::built_in();
        let prompt = registry.build_system_prompt("weekly_review").unwrap();
        assert!(prompt.contains("Weekly Review"));
        assert!(prompt.contains("JSON"));
    }

    #[test]
    fn test_build_system_prompt_goal_breakdown() {
        let registry = SkillRegistry::built_in();
        let prompt = registry.build_system_prompt("goal_breakdown").unwrap();
        assert!(prompt.contains("Goal Breakdown"));
    }

    #[test]
    fn test_build_system_prompt_unknown_skill() {
        let registry = SkillRegistry::built_in();
        let result = registry.build_system_prompt("unknown_skill");
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_skill_json_direct() {
        let json =
            r#"{"summary":"test","structured_output":{},"proposal_candidates":[],"warnings":[]}"#;
        let result = parse_skill_json(json).unwrap();
        assert_eq!(result.summary, "test");
        assert!(result.proposal_candidates.is_empty());
    }

    #[test]
    fn test_parse_skill_json_fenced_block() {
        let json = "```json\n{\"summary\":\"test\",\"structured_output\":{},\"proposal_candidates\":[],\"warnings\":[]}\n```";
        let result = parse_skill_json(json).unwrap();
        assert_eq!(result.summary, "test");
    }

    #[test]
    fn test_parse_skill_json_invalid() {
        let json = "not json at all";
        let result = parse_skill_json(json);
        assert!(result.is_err());
    }

    #[test]
    fn test_skill_manifest_fields() {
        let registry = SkillRegistry::built_in();
        let weekly = registry.get("weekly_review").unwrap();
        assert_eq!(weekly.id, "weekly_review");
        assert_eq!(weekly.name, "Weekly Review");
        assert!(!weekly.description.is_empty());
        assert_eq!(weekly.proposal_policy, "review_required");
        assert!(!weekly.input_schema.is_null());
        assert!(!weekly.output_schema.is_null());
    }

    #[test]
    fn test_skill_json_envelope_deserialization() {
        let json = r#"{
            "summary": "Weekly review completed",
            "structured_output": {"completed": 5},
            "proposal_candidates": [
                {
                    "proposal_type": "state_update",
                    "affected_path": "state.current_focus",
                    "after": "new focus",
                    "reason": "test",
                    "confidence": 0.8
                }
            ],
            "warnings": ["warning1"]
        }"#;
        let envelope: SkillJsonEnvelope = serde_json::from_str(json).unwrap();
        assert_eq!(envelope.summary, "Weekly review completed");
        assert_eq!(envelope.proposal_candidates.len(), 1);
        assert_eq!(
            envelope.proposal_candidates[0].proposal_type,
            "state_update"
        );
        assert_eq!(envelope.warnings.len(), 1);
    }
}
