const retiredDefaultCommand = (prefix: string, suffix: string) =>
  [prefix, "default", "chat", suffix].join("_");
const retiredDefaultAdapterCommand = (prefix: string, suffix: string) =>
  [prefix, "default", "chat", "adapter", suffix].filter(Boolean).join("_");

export const FORBIDDEN_ORDINARY_CHAT_COMMANDS = [
  "run_multi_strategy_agent_preview",
  "check_runtime_migration_gate",
  "check_controlled_chat_pilot_eligibility",
  "record_controlled_pilot_promotion_evidence",
  "check_controlled_pilot_promotion_readiness",
  "draft_controlled_chat_migration_plan",
  "record_controlled_chat_migration_review_decision",
  "get_controlled_chat_migration_review_decision_summary",
  "check_controlled_chat_migration_implementation_gate",
  "run_controlled_chat_migration_shadow_run",
  "record_controlled_chat_migration_shadow_review_decision",
  "get_controlled_chat_migration_shadow_review_summary",
  "check_controlled_chat_cutover_readiness",
  "run_controlled_chat_cutover_candidate",
  "record_controlled_chat_cutover_candidate_review_decision",
  "get_controlled_chat_cutover_candidate_review_summary",
  "check_controlled_chat_cutover_candidate_promotion_readiness",
  retiredDefaultCommand("get", "runtime_boundary_status"),
  retiredDefaultAdapterCommand("draft", "activation_plan"),
  retiredDefaultAdapterCommand("record", "activation_review_decision"),
  retiredDefaultAdapterCommand("get", "activation_review_summary"),
  retiredDefaultAdapterCommand("check", "activation_implementation_gate"),
  retiredDefaultAdapterCommand("get", "routing_status"),
  retiredDefaultAdapterCommand("check", "contract_harness"),
  retiredDefaultAdapterCommand("get", "ordinary_entry_preflight_status"),
  retiredDefaultAdapterCommand("check", "narrow_implementation_discussion_gate"),
  retiredDefaultAdapterCommand("draft", "narrow_implementation_plan"),
  retiredDefaultAdapterCommand("record", "narrow_implementation_plan_review_decision"),
  retiredDefaultAdapterCommand("get", "narrow_implementation_plan_review_summary"),
  retiredDefaultAdapterCommand("check", "narrow_implementation_plan_approval_readiness"),
  retiredDefaultAdapterCommand("run", "dry_run"),
  retiredDefaultAdapterCommand("record", "dry_run_review_decision"),
  retiredDefaultAdapterCommand("get", "dry_run_review_summary"),
  retiredDefaultAdapterCommand("check", "implementation_readiness"),
  retiredDefaultAdapterCommand("run", "controlled_preview"),
  retiredDefaultAdapterCommand("record", "controlled_preview_review_decision"),
  retiredDefaultAdapterCommand("get", "controlled_preview_review_summary"),
  retiredDefaultAdapterCommand("check", "controlled_preview_approval_readiness"),
  retiredDefaultAdapterCommand("draft", "cutover_implementation_plan"),
  retiredDefaultAdapterCommand("record", "cutover_plan_review_decision"),
  retiredDefaultAdapterCommand("get", "cutover_plan_review_summary"),
  retiredDefaultAdapterCommand("check", "cutover_plan_approval_readiness"),
  "get_react_beta_execution_status",
  "get_runtime_strategy_registry_status",
  "list_skills",
  "get_skill_runtime_status",
  "run_skill",
  "get_skill_run_status",
  "run_main_chat_agent_execution_v1_eval_gate",
  "run_main_chat_agent_execution_v1_final_acceptance_gate",
] as const;
